Add missing `import torch` to turbinemodel stub. (#245)
See
https://github.com/nod-ai/SHARK-TestSuite/pull/231#discussion_r1621444654.
This fixes

```
Traceback (most recent call last):
  File "D:\dev\projects\SHARK-TestSuite\e2eshark\test-run\pytorch\models\opt-125M\runmodel.py", line 145, in <module>
    torch.save(E2ESHARK_CHECK["input"], inputsavefilename)
    ^^^^^
NameError: name 'torch' is not defined
```

Individual model files had this import but did not use it directly.
Imports should be added where they are used.